---
#install pre-requisites for python3.6
  - name: Install epel-release
    yum:
      name: epel-release
      state: present

  - name: Install python34
    yum:
      name: python34
      state: present

  - name: install python34-devel
    yum:
      name: python34-devel
      state: present

#  - name: Create symbolic link
#    file:
#      src: /usr/bin/python3.4
#      dest: /usr/bin/python3
#      state: link
#    tags: symlink
